INSERT INTO contatos (empresa_id,tenant_id,nome,documento,tipo_documento,tipo,ativo) VALUES
  ('transformar','transformar','ALEX SANDRO FELICIDADE DA SILVA','nome:alex sandro felicidade da silva',NULL,'fornecedor',true),
  ('transformar','transformar','JUNIOR MICHEL ARAUJO BARRIO','nome:junior michel araujo barrio',NULL,'fornecedor',true),
  ('transformar','transformar','GONCALVES, AMARAL & CIA LTDA','nome:goncalves, amaral & cia ltda',NULL,'fornecedor',true),
  ('transformar','transformar','LEANDRO LEONCIO DE OLIVEIRA','10906617707','CPF','fornecedor',true),
  ('transformar','transformar','CARLOS ANTONIO DA SILVA','14005354769','CPF','fornecedor',true),
  ('transformar','transformar','EXTRATUS INTERMEDIAÇÕES LTDA','nome:extratus intermediações ltda',NULL,'fornecedor',true),
  ('transformar','transformar','SAMUEL SILVEIRA DOS SANTOS','19707217740','CPF','fornecedor',true),
  ('transformar','transformar','BMB MATERIAL DE CONSTRUCAO S.A.','nome:bmb material de construcao s.a.',NULL,'fornecedor',true),
  ('transformar','transformar','GEPLASTER COMERCIO DE GESSO LTDA','nome:geplaster comercio de gesso ltda',NULL,'fornecedor',true),
  ('transformar','transformar','WILFRIDO FARINA LIMENO','nome:wilfrido farina limeno',NULL,'fornecedor',true),
  ('transformar','transformar','53.425.166 JOSE GUILHERME MARQUES','nome:53.425.166 jose guilherme marques',NULL,'fornecedor',true),
  ('transformar','transformar','MARILENE DA ROCHA','nome:marilene da rocha',NULL,'fornecedor',true),
  ('transformar','transformar','FRANCISCO DEMONTIEUX PEREIRA DA SILVA 76203085391','nome:francisco demontieux pereira da silva 76203085391',NULL,'fornecedor',true),
  ('transformar','transformar','BRASPAR COMERCIO DE TINTAS LTDA','nome:braspar comercio de tintas ltda',NULL,'fornecedor',true),
  ('transformar','transformar','LUIZ MIGUEL DOS SANTOS XAVIER','14950012703','CPF','fornecedor',true),
  ('transformar','transformar','PAULA LOPES FARIAS CHAVES','12993513796','CPF','fornecedor',true),
  ('transformar','transformar','TIM S/A','nome:tim s/a',NULL,'fornecedor',true),
  ('transformar','transformar','MERCADO PAGO INSTITUICAO DE PAGAMENTO LTDA','nome:mercado pago instituicao de pagamento ltda',NULL,'fornecedor',true),
  ('transformar','transformar','NILOPOLIS ALUGUEL DE EQUIPAMENTOS LTDA.','nome:nilopolis aluguel de equipamentos ltda.',NULL,'fornecedor',true),
  ('transformar','transformar','GUILHERME MOL DIAS','nome:guilherme mol dias',NULL,'fornecedor',true),
  ('transformar','transformar','KEVIA RAQUEL RODRIGUES SEBE','nome:kevia raquel rodrigues sebe',NULL,'fornecedor',true),
  ('transformar','transformar','ITAU UNIBANCO S.A.','nome:itau unibanco s.a.',NULL,'fornecedor',true),
  ('transformar','transformar','ATACADAO DA OBRA CONSTRUFLEX MATERIAL EM GERAL E SERVICOS LTDA','nome:atacadao da obra construflex material em geral e servicos ltda',NULL,'fornecedor',true),
  ('transformar','transformar','MYSA S/A','nome:mysa s/a',NULL,'fornecedor',true),
  ('transformar','transformar','MINISTERIO DA FAZENDA','nome:ministerio da fazenda',NULL,'fornecedor',true),
  ('transformar','transformar','KALUNGA S/A','nome:kalunga s/a',NULL,'fornecedor',true),
  ('transformar','transformar','CONSELHO REGIONAL DE ENGENHARIA E AGRONOMIA DO RIO DE JANEIRO','nome:conselho regional de engenharia e agronomia do rio de janeiro',NULL,'fornecedor',true),
  ('transformar','transformar','FORTCOR TINTAS E MATERIAIS DE CONSTRUCAO DE MARECHAL LTDA','nome:fortcor tintas e materiais de construcao de marechal ltda',NULL,'fornecedor',true),
  ('transformar','transformar','EDUARDO RODRIGUES DE MOURA PEREIRA','nome:eduardo rodrigues de moura pereira',NULL,'fornecedor',true),
  ('transformar','transformar','VALDECIR SILVA VIANA','15897888779','CPF','fornecedor',true),
  ('transformar','transformar','MARECHAL MATERIAL DE CONSTRUCAO LTDA','nome:marechal material de construcao ltda',NULL,'fornecedor',true),
  ('transformar','transformar','IMAGEM MIDIA VISUAL LTDA','nome:imagem midia visual ltda',NULL,'fornecedor',true),
  ('transformar','transformar','Cândido','nome:cândido',NULL,'fornecedor',true),
  ('transformar','transformar','ISMAIR PONTES DE LIMA','nome:ismair pontes de lima',NULL,'fornecedor',true),
  ('transformar','transformar','IGREJA PENTECOSTAL RESTAURACAO EM CRISTO','nome:igreja pentecostal restauracao em cristo',NULL,'fornecedor',true),
  ('transformar','transformar','MARMORARIA PONTA PORA LTDA','nome:marmoraria ponta pora ltda',NULL,'fornecedor',true),
  ('transformar','transformar','CHRISTIAN MATHEUS SILVA DOS SANTOS','nome:christian matheus silva dos santos',NULL,'fornecedor',true),
  ('transformar','transformar','BOGU BY SISS LTDA','nome:bogu by siss ltda',NULL,'fornecedor',true),
  ('transformar','transformar','MOHAWK REVESTIMENTOS CRICIUMA LTDA','nome:mohawk revestimentos criciuma ltda',NULL,'fornecedor',true),
  ('transformar','transformar','Jaime Gonzalez','nome:jaime gonzalez',NULL,'fornecedor',true),
  ('transformar','transformar','CLARO','nome:claro',NULL,'fornecedor',true),
  ('transformar','transformar','DEPÓSITO DE MATERIAIS DE CONSTRUÇÃO NICHELE LTDA','nome:depósito de materiais de construção nichele ltda',NULL,'fornecedor',true),
  ('transformar','transformar','ALC DUARTE ARQUITETURA E INTERIORES LTDA','nome:alc duarte arquitetura e interiores ltda',NULL,'fornecedor',true),
  ('transformar','transformar','LEANDRO FIRMINO DE LIMA','nome:leandro firmino de lima',NULL,'fornecedor',true),
  ('transformar','transformar','ATUAL CARGAS TRANSPORTES LTDA','nome:atual cargas transportes ltda',NULL,'fornecedor',true),
  ('transformar','transformar','JULIO CESAR DA CONCEICAO FERNANDES','nome:julio cesar da conceicao fernandes',NULL,'fornecedor',true),
  ('transformar','transformar','NIBO SOFTWARES E CURSOS LTDA','nome:nibo softwares e cursos ltda',NULL,'fornecedor',true),
  ('transformar','transformar','RALISON QUINTANILHA DE PAULA','14053902711','CPF','fornecedor',true),
  ('transformar','transformar','CIEE - CENTRO DE INTEGRAÇÃO EMPRESA ESCOLA RJ','nome:ciee - centro de integração empresa escola rj',NULL,'fornecedor',true),
  ('transformar','transformar','FABIO GONCALVES DA SILVA','nome:fabio goncalves da silva',NULL,'fornecedor',true),
  ('transformar','transformar','65.265.453 EMILY MARTINS DOS SANTOS','nome:65.265.453 emily martins dos santos',NULL,'fornecedor',true),
  ('transformar','transformar','FACEBOOK SERVICOS ONLINE DO BRASIL LTDA.','nome:facebook servicos online do brasil ltda.',NULL,'fornecedor',true),
  ('transformar','transformar','COOPERATIVA DE CREDITO DE LIVRE ADMISSAO DA ZONA DA MATA LTDA','nome:cooperativa de credito de livre admissao da zona da mata ltda',NULL,'fornecedor',true),
  ('transformar','transformar','TAVARES GESSO E SERVICOS LTDA','nome:tavares gesso e servicos ltda',NULL,'fornecedor',true),
  ('transformar','transformar','ADIQPLUS INSTITUICAO DE PAGAMENTO LTDA','nome:adiqplus instituicao de pagamento ltda',NULL,'fornecedor',true),
  ('transformar','transformar','26.362.663 AMANDA DALCOMUNI','nome:26.362.663 amanda dalcomuni',NULL,'fornecedor',true),
  ('transformar','transformar','VANIA ROSENVALD DE AZEVEDO RAMALHO','34056033749','CPF','fornecedor',true),
  ('transformar','transformar','ALTERDATA TECNOLOGIA EM INFORMATICA LTDA','nome:alterdata tecnologia em informatica ltda',NULL,'fornecedor',true),
  ('transformar','transformar','APRIMORA AMBIENTES LTDA','nome:aprimora ambientes ltda',NULL,'fornecedor',true),
  ('transformar','transformar','GOOGLE BRASIL INTERNET LTDA.','nome:google brasil internet ltda.',NULL,'fornecedor',true),
  ('transformar','transformar','GC ASSESSORIA CONTABIL ME','nome:gc assessoria contabil me',NULL,'fornecedor',true),
  ('transformar','transformar','NETWORK NEGOCIOS LTDA','nome:network negocios ltda',NULL,'fornecedor',true),
  ('transformar','transformar','BRUNO GEOVANE DINIZ COELHO SOCIEDADE INDIVIDUAL DE ADVOCACIA','nome:bruno geovane diniz coelho sociedade individual de advocacia',NULL,'fornecedor',true),
  ('transformar','transformar','CASA DO CONSTRUTOR','nome:casa do construtor',NULL,'fornecedor',true),
  ('transformar','transformar','DIOGO FERREIRA DE LIMA 10827701756','nome:diogo ferreira de lima 10827701756',NULL,'fornecedor',true),
  ('transformar','transformar','COPIAS E CIA','nome:copias e cia',NULL,'fornecedor',true),
  ('transformar','transformar','CAMISA DIMONA E MALHAS LTDA','nome:camisa dimona e malhas ltda',NULL,'fornecedor',true),
  ('transformar','transformar','GLOBOPISO TRANSPORTES RODOVIARIOS LTDA','nome:globopiso transportes rodoviarios ltda',NULL,'fornecedor',true),
  ('transformar','transformar','ELIEZIO SANTOS DA SILVA','nome:eliezio santos da silva',NULL,'fornecedor',true),
  ('transformar','transformar','BHS COMERCIO LTDA','nome:bhs comercio ltda',NULL,'fornecedor',true),
  ('transformar','transformar','ANDERSON ANTONIO FERREIRA DE SOUZA','nome:anderson antonio ferreira de souza',NULL,'fornecedor',true),
  ('transformar','transformar','BANCO DO BRASIL SA','nome:banco do brasil sa',NULL,'fornecedor',true),
  ('transformar','transformar','LUIZ CLAUDIO BESSA RIBEIRO 02303897750','nome:luiz claudio bessa ribeiro 02303897750',NULL,'fornecedor',true),
  ('transformar','transformar','CRISTIANO ALVES DOS SANTOS','nome:cristiano alves dos santos',NULL,'fornecedor',true),
  ('transformar','transformar','BENEDITO LOPES DOS SANTOS NETO','nome:benedito lopes dos santos neto',NULL,'fornecedor',true),
  ('transformar','transformar','GEOVANI DO NASCIMENTO','nome:geovani do nascimento',NULL,'fornecedor',true),
  ('transformar','transformar','ANTONIO CARLOS ROLLA','20415176620','CPF','fornecedor',true),
  ('transformar','transformar','NOVO BAZAR MAREDU LTDA','nome:novo bazar maredu ltda',NULL,'fornecedor',true),
  ('transformar','transformar','EDGAR BARBOZA DOS SANTOS','nome:edgar barboza dos santos',NULL,'fornecedor',true),
  ('transformar','transformar','UTILIDADES DE MARECHAL HERMES LTDA','nome:utilidades de marechal hermes ltda',NULL,'fornecedor',true),
  ('transformar','transformar','TUDO DE PAPEL COMERCIO E SERVICOS LTDA','nome:tudo de papel comercio e servicos ltda',NULL,'fornecedor',true),
  ('transformar','transformar','JESMOND COMÉRCIO VAREJISTA LTDA','nome:jesmond comércio varejista ltda',NULL,'fornecedor',true),
  ('transformar','transformar','JMS REFRIGERACAO LTDA','nome:jms refrigeracao ltda',NULL,'fornecedor',true),
  ('transformar','transformar','ALGAR TELECOM S/A','nome:algar telecom s/a',NULL,'fornecedor',true),
  ('transformar','transformar','WILLIAN RAUL CARDOZO CRISTALDO','nome:willian raul cardozo cristaldo',NULL,'fornecedor',true),
  ('transformar','transformar','HOSTGATOR BRASIL LTDA.','nome:hostgator brasil ltda.',NULL,'fornecedor',true),
  ('transformar','transformar','ACACIO FELIPE MONTEIRO','10112344674','CPF','fornecedor',true),
  ('transformar','transformar','DIEGO ARTURO BENTES YAMADA IRALA','nome:diego arturo bentes yamada irala',NULL,'fornecedor',true),
  ('transformar','transformar','PANDEMONIUM BOUTIQUE RIO SUL LTDA','nome:pandemonium boutique rio sul ltda',NULL,'fornecedor',true),
  ('transformar','transformar','PAO DE ACUCAR S/A','nome:pao de acucar s/a',NULL,'fornecedor',true),
  ('transformar','transformar','GABRIEL DIAS PEREIRA DOS SANTOS','19069136767','CPF','fornecedor',true),
  ('transformar','transformar','CARLOS EDUARDO SIVA SANTOS','nome:carlos eduardo siva santos',NULL,'fornecedor',true),
  ('transformar','transformar','EDUARDO LUIS DOS SANTOS','14496323788','CPF','fornecedor',true),
  ('transformar','transformar','GLEIDSON DA SILVA','12375877780','CPF','fornecedor',true),
  ('transformar','transformar','LIGHT SERVICOS DE ELETRICIDADE S A','nome:light servicos de eletricidade s a',NULL,'fornecedor',true),
  ('transformar','transformar','VERAO TINTAS DO COMERCIO LTDA','nome:verao tintas do comercio ltda',NULL,'fornecedor',true)
RETURNING id, nome;