INSERT INTO contatos (empresa_id,tenant_id,nome,documento,tipo_documento,tipo,ativo) VALUES
  ('transformar','transformar','ALEX SANDRO FELICIDADE DA SILVA','',NULL,'fornecedor',true),
  ('transformar','transformar','JUNIOR MICHEL ARAUJO BARRIO','',NULL,'fornecedor',true),
  ('transformar','transformar','GONCALVES, AMARAL & CIA LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','LEANDRO LEONCIO DE OLIVEIRA','10906617707','CPF','fornecedor',true),
  ('transformar','transformar','CARLOS ANTONIO DA SILVA','14005354769','CPF','fornecedor',true),
  ('transformar','transformar','EXTRATUS INTERMEDIAÇÕES LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','SAMUEL SILVEIRA DOS SANTOS','19707217740','CPF','fornecedor',true),
  ('transformar','transformar','BMB MATERIAL DE CONSTRUCAO S.A.','',NULL,'fornecedor',true),
  ('transformar','transformar','GEPLASTER COMERCIO DE GESSO LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','WILFRIDO FARINA LIMENO','',NULL,'fornecedor',true),
  ('transformar','transformar','53.425.166 JOSE GUILHERME MARQUES','',NULL,'fornecedor',true),
  ('transformar','transformar','MARILENE DA ROCHA','',NULL,'fornecedor',true),
  ('transformar','transformar','FRANCISCO DEMONTIEUX PEREIRA DA SILVA 76203085391','',NULL,'fornecedor',true),
  ('transformar','transformar','BRASPAR COMERCIO DE TINTAS LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','LUIZ MIGUEL DOS SANTOS XAVIER','14950012703','CPF','fornecedor',true),
  ('transformar','transformar','PAULA LOPES FARIAS CHAVES','12993513796','CPF','fornecedor',true),
  ('transformar','transformar','TIM S/A','',NULL,'fornecedor',true),
  ('transformar','transformar','MERCADO PAGO INSTITUICAO DE PAGAMENTO LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','NILOPOLIS ALUGUEL DE EQUIPAMENTOS LTDA.','',NULL,'fornecedor',true),
  ('transformar','transformar','GUILHERME MOL DIAS','',NULL,'fornecedor',true),
  ('transformar','transformar','KEVIA RAQUEL RODRIGUES SEBE','',NULL,'fornecedor',true),
  ('transformar','transformar','ITAU UNIBANCO S.A.','',NULL,'fornecedor',true),
  ('transformar','transformar','ATACADAO DA OBRA CONSTRUFLEX MATERIAL EM GERAL E SERVICOS LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','MYSA S/A','',NULL,'fornecedor',true),
  ('transformar','transformar','MINISTERIO DA FAZENDA','',NULL,'fornecedor',true),
  ('transformar','transformar','KALUNGA S/A','',NULL,'fornecedor',true),
  ('transformar','transformar','CONSELHO REGIONAL DE ENGENHARIA E AGRONOMIA DO RIO DE JANEIRO','',NULL,'fornecedor',true),
  ('transformar','transformar','FORTCOR TINTAS E MATERIAIS DE CONSTRUCAO DE MARECHAL LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','EDUARDO RODRIGUES DE MOURA PEREIRA','',NULL,'fornecedor',true),
  ('transformar','transformar','VALDECIR SILVA VIANA','15897888779','CPF','fornecedor',true),
  ('transformar','transformar','MARECHAL MATERIAL DE CONSTRUCAO LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','IMAGEM MIDIA VISUAL LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','Cândido','',NULL,'fornecedor',true),
  ('transformar','transformar','ISMAIR PONTES DE LIMA','',NULL,'fornecedor',true),
  ('transformar','transformar','IGREJA PENTECOSTAL RESTAURACAO EM CRISTO','',NULL,'fornecedor',true),
  ('transformar','transformar','MARMORARIA PONTA PORA LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','CHRISTIAN MATHEUS SILVA DOS SANTOS','',NULL,'fornecedor',true),
  ('transformar','transformar','BOGU BY SISS LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','MOHAWK REVESTIMENTOS CRICIUMA LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','Jaime Gonzalez','',NULL,'fornecedor',true),
  ('transformar','transformar','CLARO','',NULL,'fornecedor',true),
  ('transformar','transformar','DEPÓSITO DE MATERIAIS DE CONSTRUÇÃO NICHELE LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','ALC DUARTE ARQUITETURA E INTERIORES LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','LEANDRO FIRMINO DE LIMA','',NULL,'fornecedor',true),
  ('transformar','transformar','ATUAL CARGAS TRANSPORTES LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','JULIO CESAR DA CONCEICAO FERNANDES','',NULL,'fornecedor',true),
  ('transformar','transformar','NIBO SOFTWARES E CURSOS LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','RALISON QUINTANILHA DE PAULA','14053902711','CPF','fornecedor',true),
  ('transformar','transformar','CIEE - CENTRO DE INTEGRAÇÃO EMPRESA ESCOLA RJ','',NULL,'fornecedor',true),
  ('transformar','transformar','FABIO GONCALVES DA SILVA','',NULL,'fornecedor',true),
  ('transformar','transformar','65.265.453 EMILY MARTINS DOS SANTOS','',NULL,'fornecedor',true),
  ('transformar','transformar','FACEBOOK SERVICOS ONLINE DO BRASIL LTDA.','',NULL,'fornecedor',true),
  ('transformar','transformar','COOPERATIVA DE CREDITO DE LIVRE ADMISSAO DA ZONA DA MATA LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','TAVARES GESSO E SERVICOS LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','ADIQPLUS INSTITUICAO DE PAGAMENTO LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','26.362.663 AMANDA DALCOMUNI','',NULL,'fornecedor',true),
  ('transformar','transformar','VANIA ROSENVALD DE AZEVEDO RAMALHO','34056033749','CPF','fornecedor',true),
  ('transformar','transformar','ALTERDATA TECNOLOGIA EM INFORMATICA LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','APRIMORA AMBIENTES LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','GOOGLE BRASIL INTERNET LTDA.','',NULL,'fornecedor',true),
  ('transformar','transformar','GC ASSESSORIA CONTABIL ME','',NULL,'fornecedor',true),
  ('transformar','transformar','NETWORK NEGOCIOS LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','BRUNO GEOVANE DINIZ COELHO SOCIEDADE INDIVIDUAL DE ADVOCACIA','',NULL,'fornecedor',true),
  ('transformar','transformar','CASA DO CONSTRUTOR','',NULL,'fornecedor',true),
  ('transformar','transformar','DIOGO FERREIRA DE LIMA 10827701756','',NULL,'fornecedor',true),
  ('transformar','transformar','COPIAS E CIA','',NULL,'fornecedor',true),
  ('transformar','transformar','CAMISA DIMONA E MALHAS LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','GLOBOPISO TRANSPORTES RODOVIARIOS LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','ELIEZIO SANTOS DA SILVA','',NULL,'fornecedor',true),
  ('transformar','transformar','BHS COMERCIO LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','ANDERSON ANTONIO FERREIRA DE SOUZA','',NULL,'fornecedor',true),
  ('transformar','transformar','BANCO DO BRASIL SA','',NULL,'fornecedor',true),
  ('transformar','transformar','LUIZ CLAUDIO BESSA RIBEIRO 02303897750','',NULL,'fornecedor',true),
  ('transformar','transformar','CRISTIANO ALVES DOS SANTOS','',NULL,'fornecedor',true),
  ('transformar','transformar','BENEDITO LOPES DOS SANTOS NETO','',NULL,'fornecedor',true),
  ('transformar','transformar','GEOVANI DO NASCIMENTO','',NULL,'fornecedor',true),
  ('transformar','transformar','ANTONIO CARLOS ROLLA','20415176620','CPF','fornecedor',true),
  ('transformar','transformar','NOVO BAZAR MAREDU LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','EDGAR BARBOZA DOS SANTOS','',NULL,'fornecedor',true),
  ('transformar','transformar','UTILIDADES DE MARECHAL HERMES LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','TUDO DE PAPEL COMERCIO E SERVICOS LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','JESMOND COMÉRCIO VAREJISTA LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','JMS REFRIGERACAO LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','ALGAR TELECOM S/A','',NULL,'fornecedor',true),
  ('transformar','transformar','WILLIAN RAUL CARDOZO CRISTALDO','',NULL,'fornecedor',true),
  ('transformar','transformar','HOSTGATOR BRASIL LTDA.','',NULL,'fornecedor',true),
  ('transformar','transformar','ACACIO FELIPE MONTEIRO','10112344674','CPF','fornecedor',true),
  ('transformar','transformar','DIEGO ARTURO BENTES YAMADA IRALA','',NULL,'fornecedor',true),
  ('transformar','transformar','PANDEMONIUM BOUTIQUE RIO SUL LTDA','',NULL,'fornecedor',true),
  ('transformar','transformar','PAO DE ACUCAR S/A','',NULL,'fornecedor',true),
  ('transformar','transformar','GABRIEL DIAS PEREIRA DOS SANTOS','19069136767','CPF','fornecedor',true),
  ('transformar','transformar','CARLOS EDUARDO SIVA SANTOS','',NULL,'fornecedor',true),
  ('transformar','transformar','EDUARDO LUIS DOS SANTOS','14496323788','CPF','fornecedor',true),
  ('transformar','transformar','GLEIDSON DA SILVA','12375877780','CPF','fornecedor',true),
  ('transformar','transformar','LIGHT SERVICOS DE ELETRICIDADE S A','',NULL,'fornecedor',true),
  ('transformar','transformar','VERAO TINTAS DO COMERCIO LTDA','',NULL,'fornecedor',true);
