// CID-10 — Códigos mais frequentes em atestados médicos no Brasil
// Fonte: CID-10 OMS / MS-BR. Ordenados por categoria.
export const CID10_COMUM = [
  // Infecções respiratórias
  { codigo: 'J00', descricao: 'Rinofaringite aguda (resfriado comum)' },
  { codigo: 'J02.9', descricao: 'Faringite aguda não especificada' },
  { codigo: 'J03.9', descricao: 'Amigdalite aguda não especificada' },
  { codigo: 'J04.0', descricao: 'Laringite aguda' },
  { codigo: 'J04.1', descricao: 'Traqueíte aguda' },
  { codigo: 'J06.9', descricao: 'Infecção aguda das vias aéreas superiores não especificada' },
  { codigo: 'J10', descricao: 'Influenza devida a vírus influenza identificado' },
  { codigo: 'J11', descricao: 'Influenza devida a vírus não identificado' },
  { codigo: 'J18.9', descricao: 'Pneumonia não especificada' },
  { codigo: 'J20.9', descricao: 'Bronquite aguda não especificada' },
  { codigo: 'J40', descricao: 'Bronquite não especificada como aguda ou crônica' },
  { codigo: 'J44.1', descricao: 'Doença pulmonar obstrutiva crônica com exacerbação aguda' },
  { codigo: 'J45.0', descricao: 'Asma predominantemente alérgica' },
  { codigo: 'J45.1', descricao: 'Asma não alérgica' },
  // Digestivo
  { codigo: 'A09', descricao: 'Diarreia e gastroenterite de origem infecciosa presumível' },
  { codigo: 'K21.0', descricao: 'Doença do refluxo gastroesofágico com esofagite' },
  { codigo: 'K25.3', descricao: 'Úlcera gástrica aguda sem hemorragia nem perfuração' },
  { codigo: 'K29.7', descricao: 'Gastrite não especificada' },
  { codigo: 'K35.9', descricao: 'Apendicite aguda não especificada' },
  { codigo: 'K57.30', descricao: 'Doença diverticular do intestino sem especificação' },
  { codigo: 'K59.0', descricao: 'Constipação intestinal' },
  { codigo: 'K70.0', descricao: 'Fígado gorduroso alcoólico' },
  { codigo: 'K74.6', descricao: 'Cirrose hepática não especificada' },
  { codigo: 'K80.2', descricao: 'Calculose da vesícula biliar sem colecistite' },
  { codigo: 'K92.1', descricao: 'Melena' },
  // Osteomuscular / muito frequente em construção civil
  { codigo: 'M10.9', descricao: 'Gota não especificada' },
  { codigo: 'M16.9', descricao: 'Coxartrose não especificada' },
  { codigo: 'M17.9', descricao: 'Gonartrose não especificada' },
  { codigo: 'M19.9', descricao: 'Artrose não especificada' },
  { codigo: 'M25.5', descricao: 'Dor articular' },
  { codigo: 'M40.0', descricao: 'Cifose postural' },
  { codigo: 'M47.8', descricao: 'Espondilose com outras mielopatias' },
  { codigo: 'M48.0', descricao: 'Estenose do canal espinhal' },
  { codigo: 'M51.1', descricao: 'Degeneração de disco intervertebral lombar e outros' },
  { codigo: 'M54.2', descricao: 'Cervicalgia' },
  { codigo: 'M54.3', descricao: 'Ciática' },
  { codigo: 'M54.4', descricao: 'Lumbago com ciática' },
  { codigo: 'M54.5', descricao: 'Dor lombar baixa (lombalgia)' },
  { codigo: 'M54.6', descricao: 'Dor na coluna torácica' },
  { codigo: 'M60.9', descricao: 'Miosite não especificada' },
  { codigo: 'M65.9', descricao: 'Sinovite e tenossinovite não especificada' },
  { codigo: 'M70.0', descricao: 'Sinovite crepitante do punho e da mão' },
  { codigo: 'M75.1', descricao: 'Síndrome do manguito rotador' },
  { codigo: 'M79.1', descricao: 'Mialgia' },
  { codigo: 'M79.3', descricao: 'Paniculite não especificada' },
  { codigo: 'M79.6', descricao: 'Dor nos membros' },
  // Lesões e traumatismos (muito frequente em construção)
  { codigo: 'S00.0', descricao: 'Traumatismo superficial do couro cabeludo' },
  { codigo: 'S01.0', descricao: 'Ferimento aberto do couro cabeludo' },
  { codigo: 'S09.9', descricao: 'Traumatismo da cabeça não especificado' },
  { codigo: 'S20.0', descricao: 'Contusão da mama' },
  { codigo: 'S30.0', descricao: 'Contusão do dorso e da pelve' },
  { codigo: 'S40.0', descricao: 'Contusão do ombro e do braço' },
  { codigo: 'S50.0', descricao: 'Contusão do cotovelo' },
  { codigo: 'S60.0', descricao: 'Contusão do dedo sem lesão ungueal' },
  { codigo: 'S70.0', descricao: 'Contusão do quadril' },
  { codigo: 'S80.0', descricao: 'Contusão do joelho' },
  { codigo: 'S82.0', descricao: 'Fratura da rótula' },
  { codigo: 'S82.6', descricao: 'Fratura do maléolo lateral' },
  { codigo: 'S90.0', descricao: 'Contusão do tornozelo' },
  { codigo: 'S92.0', descricao: 'Fratura do calcâneo' },
  { codigo: 'T14.0', descricao: 'Ferimento de região do corpo não especificada' },
  { codigo: 'T14.1', descricao: 'Fratura de região do corpo não especificada' },
  { codigo: 'T14.2', descricao: 'Luxação de região do corpo não especificada' },
  { codigo: 'T14.3', descricao: 'Entorse e distensão de região do corpo não especificada' },
  // Mentais / Psiquiátricos
  { codigo: 'F10.0', descricao: 'Transtornos mentais e comportamentais devidos ao álcool - intoxicação aguda' },
  { codigo: 'F10.2', descricao: 'Transtornos mentais devidos ao álcool - síndrome de dependência' },
  { codigo: 'F17.2', descricao: 'Transtornos mentais devidos ao tabaco - síndrome de dependência' },
  { codigo: 'F20.0', descricao: 'Esquizofrenia paranoide' },
  { codigo: 'F29', descricao: 'Psicose não orgânica não especificada' },
  { codigo: 'F31.9', descricao: 'Transtorno afetivo bipolar não especificado' },
  { codigo: 'F32.0', descricao: 'Episódio depressivo leve' },
  { codigo: 'F32.1', descricao: 'Episódio depressivo moderado' },
  { codigo: 'F32.2', descricao: 'Episódio depressivo grave sem sintomas psicóticos' },
  { codigo: 'F33.1', descricao: 'Transtorno depressivo recorrente moderado' },
  { codigo: 'F40.0', descricao: 'Agorafobia' },
  { codigo: 'F40.1', descricao: 'Fobias sociais' },
  { codigo: 'F41.0', descricao: 'Transtorno de pânico' },
  { codigo: 'F41.1', descricao: 'Transtorno de ansiedade generalizada' },
  { codigo: 'F41.2', descricao: 'Transtorno misto ansioso e depressivo' },
  { codigo: 'F43.1', descricao: 'Transtorno de estresse pós-traumático' },
  { codigo: 'F43.2', descricao: 'Transtorno de adaptação' },
  { codigo: 'F43.9', descricao: 'Reação ao estresse grave não especificada' },
  { codigo: 'F48.0', descricao: 'Neurastenia' },
  { codigo: 'F51.0', descricao: 'Insônia não orgânica' },
  // Circulatório
  { codigo: 'I10', descricao: 'Hipertensão essencial (primária)' },
  { codigo: 'I11.9', descricao: 'Doença cardíaca hipertensiva sem insuficiência cardíaca' },
  { codigo: 'I20.0', descricao: 'Angina instável' },
  { codigo: 'I21.9', descricao: 'Infarto agudo do miocárdio não especificado' },
  { codigo: 'I25.1', descricao: 'Doença aterosclerótica do coração' },
  { codigo: 'I49.9', descricao: 'Arritmia cardíaca não especificada' },
  { codigo: 'I50.0', descricao: 'Insuficiência cardíaca congestiva' },
  { codigo: 'I63.9', descricao: 'Infarto cerebral não especificado' },
  { codigo: 'I64', descricao: 'Acidente vascular cerebral não especificado' },
  { codigo: 'I83.9', descricao: 'Varizes dos membros inferiores sem úlcera e sem inflamação' },
  // Endócrino
  { codigo: 'E10.9', descricao: 'Diabetes mellitus tipo 1 sem complicações' },
  { codigo: 'E11.9', descricao: 'Diabetes mellitus tipo 2 sem complicações' },
  { codigo: 'E14.9', descricao: 'Diabetes mellitus não especificado sem complicações' },
  { codigo: 'E65', descricao: 'Adiposidade localizada' },
  { codigo: 'E66.0', descricao: 'Obesidade devida a excesso de calorias' },
  { codigo: 'E78.0', descricao: 'Hipercolesterolemia pura' },
  { codigo: 'E78.5', descricao: 'Hiperlipidemia não especificada' },
  // Urinário / Renal
  { codigo: 'N10', descricao: 'Nefrite tubulointersticial aguda' },
  { codigo: 'N20.0', descricao: 'Calculose do rim' },
  { codigo: 'N20.1', descricao: 'Calculose do ureter' },
  { codigo: 'N23', descricao: 'Cólica renal não especificada' },
  { codigo: 'N30.0', descricao: 'Cistite aguda' },
  { codigo: 'N39.0', descricao: 'Infecção do trato urinário de localização não especificada' },
  // Neurológico
  { codigo: 'G43.9', descricao: 'Enxaqueca não especificada' },
  { codigo: 'G44.2', descricao: 'Cefaleia tensional' },
  { codigo: 'G44.9', descricao: 'Cefaleia não especificada' },
  { codigo: 'G54.1', descricao: 'Afecções das raízes nervosas lombossacrais não classificadas em outra parte' },
  { codigo: 'G54.4', descricao: 'Síndrome da cauda equina' },
  { codigo: 'G56.0', descricao: 'Síndrome do túnel do carpo' },
  { codigo: 'G57.0', descricao: 'Ciática — lesão do nervo ciático' },
  { codigo: 'G89.2', descricao: 'Dor crônica' },
  // Olhos / Otorrinolaringologia
  { codigo: 'H10.9', descricao: 'Conjuntivite não especificada' },
  { codigo: 'H52.1', descricao: 'Miopia' },
  { codigo: 'H60.9', descricao: 'Otite externa não especificada' },
  { codigo: 'H65.9', descricao: 'Otite média não supurativa não especificada' },
  { codigo: 'H66.9', descricao: 'Otite média não especificada' },
  { codigo: 'H81.1', descricao: 'Vertigem paroxística benigna' },
  { codigo: 'H81.3', descricao: 'Outras vertigens periféricas' },
  { codigo: 'H81.9', descricao: 'Transtorno da função vestibular não especificado' },
  // Pele
  { codigo: 'L01.0', descricao: 'Impetigo (causado por Staphylococcus aureus)' },
  { codigo: 'L02.9', descricao: 'Abscesso cutâneo, furúnculo e antraz não especificados' },
  { codigo: 'L03.1', descricao: 'Celulite do membro' },
  { codigo: 'L20.9', descricao: 'Dermatite atópica não especificada' },
  { codigo: 'L23.9', descricao: 'Dermatite alérgica de contato não especificada' },
  { codigo: 'L30.9', descricao: 'Dermatite não especificada' },
  { codigo: 'L50.9', descricao: 'Urticária não especificada' },
  // Saúde mental trabalho / doenças ocupacionais
  { codigo: 'Z73.0', descricao: 'Esgotamento — Burnout' },
  { codigo: 'Z73.3', descricao: 'Estresse não classificado em outra parte' },
  // COVID-19
  { codigo: 'U07.1', descricao: 'COVID-19, vírus identificado' },
  { codigo: 'U07.2', descricao: 'COVID-19, vírus não identificado' },
  // Dengue / Arboviroses
  { codigo: 'A90', descricao: 'Dengue clássica' },
  { codigo: 'A91', descricao: 'Febre hemorrágica devida ao vírus do dengue' },
  { codigo: 'A92.0', descricao: 'Infecção pelo vírus Chikungunya' },
  { codigo: 'A928', descricao: 'Outras febres por vírus transmitidos por mosquitos (Zika)' },
  // Procedimentos cirúrgicos / pós-operatório
  { codigo: 'Z48.0', descricao: 'Cuidados com curativos e pontos de sutura' },
  { codigo: 'Z48.8', descricao: 'Outros cuidados especificados de cirurgia' },
  { codigo: 'Z48.9', descricao: 'Cuidados pós-operatório não especificado' },
  { codigo: 'Z96.6', descricao: 'Presença de implantes ortopédicos articulares' },
]
